{% set name = "tld" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tld-{{ version }}.tar.gz
  sha256: 75ec00936cbcf564f67361c41713363440b6c4ef0f0c1592b5b0fbe72c17a350

build:
  number: 0
  noarch: python
  entry_points:
    - update-tld-names = tld.utils:update_tld_names_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - tld
  commands:
    - pip check
    - update-tld-names --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/barseghyanartur/tld
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: LICENSE_LGPL_2.1.txt
  summary: Extracts the top level domain (TLD) from the URL given.
  description: |
    Extract the top level domain (TLD) from the URL given. List of TLD 
    names is taken from Public Suffix.
  doc_url: http://tld.readthedocs.io/
  dev_url: https://github.com/barseghyanartur/tld

extra:
  recipe-maintainers:
    - jan-janssen
